# Generated by Django 4.2.11 on 2024-05-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0002_article_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at']},
        ),
    ]
